showcase:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: showcase_user
      password: showcase_password
      port: 5432
      dbname: showcase_db
      schema: analytics_dev
      threads: 4
      keepalives_idle: 0
      search_path: "analytics_dev,public"
    
    prod:
      type: postgres
      host: postgres
      user: showcase_user
      password: showcase_password
      port: 5432
      dbname: showcase_db
      schema: analytics_prod
      threads: 8
      keepalives_idle: 0
      search_path: "analytics_prod,public"
    
    test:
      type: postgres
      host: postgres
      user: showcase_user
      password: showcase_password
      port: 5432
      dbname: showcase_db
      schema: analytics_test
      threads: 2
      keepalives_idle: 0
      search_path: "analytics_test,public" 