version: 2

models:
  - name: direct_grocery_connector_store_sales
    description: "Direct view of grocery connector store sales data with basic filtering"
    columns:
      - name: account_id
        description: "Account identifier"
        tests:
          - not_null
      - name: connector_id
        description: "Connector identifier"
        tests:
          - not_null
      - name: ingestion_timestamp
        description: "Timestamp when data was ingested"
        tests:
          - not_null
      - name: report_date
        description: "Date of the sales report"
        tests:
          - not_null
      - name: store_key
        description: "Store business key"
        tests:
          - not_null
      - name: product_key
        description: "Product business key"
        tests:
          - not_null
      - name: upc
        description: "Universal Product Code"
      - name: begin_date
        description: "Period begin date"
      - name: end_date
        description: "Period end date"
      - name: sales_dollars
        description: "Total sales dollars"
      - name: sales_units
        description: "Total sales units"
      - name: regular_sales_dollars
        description: "Regular sales dollars"
      - name: regular_sales_units
        description: "Regular sales units"
      - name: promotional_sales_dollars
        description: "Promotional sales dollars"
      - name: promotional_sales_units
        description: "Promotional sales units"
    tests:
      - dbt_utils.data_freshness:
          datepart: hour
          interval: 26
          field: ingestion_timestamp
          config:
            severity: warn

  - name: direct_grocery_connector_store_inventory
    description: "Direct view of grocery connector store inventory data with basic filtering"
    columns:
      - name: account_id
        description: "Account identifier"
        tests:
          - not_null
      - name: connector_id
        description: "Connector identifier"
        tests:
          - not_null
      - name: ingestion_timestamp
        description: "Timestamp when data was ingested"
        tests:
          - not_null
      - name: report_date
        description: "Date of the inventory report"
        tests:
          - not_null
      - name: store_key
        description: "Store business key"
        tests:
          - not_null
      - name: product_key
        description: "Product business key"
        tests:
          - not_null
      - name: upc
        description: "Universal Product Code"
      - name: on_hand_units
        description: "On hand inventory units"
      - name: on_hand_dollars
        description: "On hand inventory dollars"
      - name: on_order_units
        description: "On order inventory units"
      - name: on_order_dollars
        description: "On order inventory dollars"
      - name: allocated_units
        description: "Allocated inventory units"
      - name: available_units
        description: "Available inventory units"
    tests:
      - dbt_utils.data_freshness:
          datepart: hour
          interval: 26
          field: ingestion_timestamp
          config:
            severity: warn

  - name: direct_grocery_connector_product_master
    description: "Direct view of grocery connector product master data with basic filtering"
    columns:
      - name: account_id
        description: "Account identifier"
        tests:
          - not_null
      - name: connector_id
        description: "Connector identifier"
        tests:
          - not_null
      - name: ingestion_timestamp
        description: "Timestamp when data was ingested"
        tests:
          - not_null
      - name: report_date
        description: "Date of the product master report"
        tests:
          - not_null
      - name: product_key
        description: "Product business key"
        tests:
          - not_null
      - name: product_name
        description: "Product name"
      - name: brand_key
        description: "Brand business key"
      - name: brand
        description: "Brand name"
      - name: category_key
        description: "Category business key"
      - name: category
        description: "Category name"
      - name: subcategory_key
        description: "Subcategory business key"
      - name: subcategory
        description: "Subcategory name"
      - name: supplier_key
        description: "Supplier business key"
      - name: supplier_name
        description: "Supplier name"
      - name: upc
        description: "Universal Product Code"
      - name: pack_size
        description: "Product pack size"
      - name: unit_of_measure
        description: "Unit of measure"
      - name: product_description
        description: "Product description"
      - name: product_status
        description: "Product status"
    tests:
      - dbt_utils.data_freshness:
          datepart: hour
          interval: 26
          field: ingestion_timestamp
          config:
            severity: warn

  - name: direct_grocery_connector_store_master
    description: "Direct view of grocery connector store master data with basic filtering"
    columns:
      - name: account_id
        description: "Account identifier"
        tests:
          - not_null
      - name: connector_id
        description: "Connector identifier"
        tests:
          - not_null
      - name: ingestion_timestamp
        description: "Timestamp when data was ingested"
        tests:
          - not_null
      - name: report_date
        description: "Date of the store master report"
        tests:
          - not_null
      - name: chain_key
        description: "Chain business key"
      - name: chain
        description: "Chain name"
      - name: store_key
        description: "Store business key"
        tests:
          - not_null
      - name: store_name
        description: "Store name"
      - name: store_number
        description: "Store number"
      - name: store_type
        description: "Store type"
      - name: store_address
        description: "Store address"
      - name: store_city
        description: "Store city"
      - name: store_state
        description: "Store state"
      - name: store_zip
        description: "Store zip code"
      - name: store_country
        description: "Store country"
      - name: store_latitude
        description: "Store latitude"
      - name: store_longitude
        description: "Store longitude"
      - name: store_manager
        description: "Store manager name"
      - name: store_phone
        description: "Store phone number"
      - name: store_status
        description: "Store status"
      - name: district_key
        description: "District business key"
      - name: district
        description: "District name"
      - name: region_key
        description: "Region business key"
      - name: region
        description: "Region name"
    tests:
      - dbt_utils.data_freshness:
          datepart: hour
          interval: 26
          field: ingestion_timestamp
          config:
            severity: warn 