version: 2

models:
  # Fact Tables
  - name: normalized_retail_connector_fact_sales
    description: "Normalized sales fact table with surrogate keys and foreign key relationships"
    columns:
      - name: sales_id
        description: "Sales surrogate key"
        tests:
          - unique
          - not_null
      - name: store_id
        description: "Store surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_store')
              field: store_id
      - name: product_id
        description: "Product surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product')
              field: product_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: date_key
        description: "Date key for sales period"
      - name: sales_amount
        description: "Total sales amount"
      - name: sales_quantity
        description: "Total sales quantity"

  - name: normalized_retail_connector_fact_inventory_store
    description: "Normalized inventory fact table with surrogate keys and foreign key relationships"
    columns:
      - name: inventory_id
        description: "Inventory surrogate key"
        tests:
          - unique
          - not_null
      - name: store_id
        description: "Store surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_store')
              field: store_id
      - name: product_id
        description: "Product surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product')
              field: product_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: date_key
        description: "Date key for inventory period"
      - name: on_hand_quantity
        description: "On hand inventory quantity"
      - name: on_hand_amount
        description: "On hand inventory amount"
      - name: on_order_quantity
        description: "On order inventory quantity"
      - name: on_order_amount
        description: "On order inventory amount"

  # Dimension Tables
  - name: normalized_retail_connector_dim_product
    description: "Normalized product dimension with surrogate keys and foreign key relationships"
    columns:
      - name: product_id
        description: "Product surrogate key"
        tests:
          - unique
          - not_null
      - name: product_brand_id
        description: "Product brand surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product_brand')
              field: product_brand_id
      - name: product_subcategory_id
        description: "Product subcategory surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product_subcategory')
              field: product_subcategory_id
      - name: product_supplier_id
        description: "Product supplier surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product_supplier')
              field: product_supplier_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: product_key
        description: "Product business key"
      - name: product
        description: "Product name"
      - name: upc
        description: "Universal Product Code"
      - name: pack_size
        description: "Product pack size"
      - name: unit_of_measure
        description: "Unit of measure"
      - name: product_description
        description: "Product description"
      - name: product_status
        description: "Product status"

  - name: normalized_retail_connector_dim_store
    description: "Normalized store dimension with surrogate keys and foreign key relationships"
    columns:
      - name: store_id
        description: "Store surrogate key"
        tests:
          - unique
          - not_null
      - name: store_chain_id
        description: "Store chain surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_store_chain')
              field: store_chain_id
      - name: store_district_id
        description: "Store district surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_store_district')
              field: store_district_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: store_key
        description: "Store business key"
      - name: store_name
        description: "Store name"
      - name: store_number
        description: "Store number"
      - name: store_type
        description: "Store type"
      - name: store_address
        description: "Store address"
      - name: store_city
        description: "Store city"
      - name: store_state
        description: "Store state"
      - name: store_zip
        description: "Store zip code"
      - name: store_country
        description: "Store country"
      - name: store_latitude
        description: "Store latitude"
      - name: store_longitude
        description: "Store longitude"
      - name: store_manager
        description: "Store manager name"
      - name: store_phone
        description: "Store phone number"
      - name: store_status
        description: "Store status"

  # Lookup Dimensions
  - name: normalized_retail_connector_dim_product_brand
    description: "Product brand dimension"
    columns:
      - name: product_brand_id
        description: "Product brand surrogate key"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: product_brand_key
        description: "Product brand business key"
      - name: product_brand
        description: "Product brand name"

  - name: normalized_retail_connector_dim_product_category
    description: "Product category dimension"
    columns:
      - name: product_category_id
        description: "Product category surrogate key"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: product_category_key
        description: "Product category business key"
      - name: product_category
        description: "Product category name"

  - name: normalized_retail_connector_dim_product_subcategory
    description: "Product subcategory dimension"
    columns:
      - name: product_subcategory_id
        description: "Product subcategory surrogate key"
        tests:
          - unique
          - not_null
      - name: product_category_id
        description: "Product category surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_product_category')
              field: product_category_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: product_subcategory_key
        description: "Product subcategory business key"
      - name: product_subcategory
        description: "Product subcategory name"

  - name: normalized_retail_connector_dim_product_supplier
    description: "Product supplier dimension"
    columns:
      - name: product_supplier_id
        description: "Product supplier surrogate key"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: product_supplier_key
        description: "Product supplier business key"
      - name: product_supplier
        description: "Product supplier name"

  - name: normalized_retail_connector_dim_store_chain
    description: "Store chain dimension"
    columns:
      - name: store_chain_id
        description: "Store chain surrogate key"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: store_chain_key
        description: "Store chain business key"
      - name: store_chain
        description: "Store chain name"

  - name: normalized_retail_connector_dim_store_district
    description: "Store district dimension"
    columns:
      - name: store_district_id
        description: "Store district surrogate key"
        tests:
          - unique
          - not_null
      - name: store_region_id
        description: "Store region surrogate key (foreign key)"
        tests:
          - relationships:
              to: ref('normalized_retail_connector_dim_store_region')
              field: store_region_id
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: store_district_key
        description: "Store district business key"
      - name: store_district
        description: "Store district name"

  - name: normalized_retail_connector_dim_store_region
    description: "Store region dimension"
    columns:
      - name: store_region_id
        description: "Store region surrogate key"
        tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
      - name: connector_id
        description: "Connector identifier"
      - name: store_region_key
        description: "Store region business key"
      - name: store_region
        description: "Store region name" 