version: 2

models:
  - name: harmonized_fact_sales
    description: "Harmonized sales fact table across all connectors"
    columns:
      - name: sales_id
        description: "Harmonized sales surrogate key"
      - name: retailer_id
        description: "Harmonized retailer identifier"
      - name: store_id
        description: "Harmonized store surrogate key"
      - name: product_id
        description: "Harmonized product surrogate key"
      - name: date_key
        description: "Date key for sales period"
      - name: sales_amount
        description: "Total sales amount"
      - name: sales_quantity
        description: "Total sales quantity"
      - name: connector_name
        description: "Source connector name"

  - name: harmonized_fact_inventory
    description: "Harmonized inventory fact table across all connectors"
    columns:
      - name: inventory_id
        description: "Harmonized inventory surrogate key"
      - name: retailer_id
        description: "Harmonized retailer identifier"
      - name: store_id
        description: "Harmonized store surrogate key"
      - name: product_id
        description: "Harmonized product surrogate key"
      - name: date_key
        description: "Date key for inventory period"
      - name: on_hand_quantity
        description: "On hand inventory quantity"
      - name: on_hand_amount
        description: "On hand inventory amount"
      - name: connector_name
        description: "Source connector name"

  - name: harmonized_dim_product
    description: "Harmonized product dimension across all connectors"
    columns:
      - name: product_id
        description: "Harmonized product surrogate key"
      - name: retailer_id
        description: "Harmonized retailer identifier"
      - name: product_key
        description: "Product business key"
      - name: product
        description: "Product name"
      - name: product_brand
        description: "Product brand name"
      - name: product_category
        description: "Product category name"
      - name: product_subcategory
        description: "Product subcategory name"
      - name: product_supplier
        description: "Product supplier name"
      - name: upc
        description: "Universal Product Code"
      - name: pack_size
        description: "Product pack size"
      - name: unit_of_measure
        description: "Unit of measure"
      - name: product_description
        description: "Product description"
      - name: product_status
        description: "Product status"
      - name: connector_name
        description: "Source connector name"

  - name: harmonized_dim_store
    description: "Harmonized store dimension across all connectors"
    columns:
      - name: store_id
        description: "Harmonized store surrogate key"
      - name: retailer_id
        description: "Harmonized retailer identifier"
      - name: store_key
        description: "Store business key"
      - name: store_name
        description: "Store name"
      - name: store_chain
        description: "Store chain name"
      - name: store_district
        description: "Store district name"
      - name: store_region
        description: "Store region name"
      - name: store_number
        description: "Store number"
      - name: store_type
        description: "Store type"
      - name: store_address
        description: "Store address"
      - name: store_city
        description: "Store city"
      - name: store_state
        description: "Store state"
      - name: store_zip
        description: "Store zip code"
      - name: store_country
        description: "Store country"
      - name: store_latitude
        description: "Store latitude"
      - name: store_longitude
        description: "Store longitude"
      - name: store_manager
        description: "Store manager name"
      - name: store_phone
        description: "Store phone number"
      - name: store_status
        description: "Store status"
      - name: connector_name
        description: "Source connector name"

  - name: harmonized_dim_retailer
    description: "Harmonized retailer dimension for cross-connector identification"
    columns:
      - name: retailer_id
        description: "Harmonized retailer identifier"
      - name: retailer_name
        description: "Retailer name"
      - name: retailer_type
        description: "Retailer type"
      - name: connector_name
        description: "Source connector name" 